/*
 * SkeletonStreaming.h
 *
 *  Created on: Apr 19, 2013
 *      Author: seungsu
 */

#ifndef SKELETONSTREAMING_H_
#define SKELETONSTREAMING_H_

#define THROWING_STATE_TOPIC "/throwing/state"
#define THROWING_CMD_TOPIC "/throwing/cmd"

enum ENUM_VISIONCOMMAND{VISIONCOMMAND_STARTRECORDING, VISIONCOMMAND_STOPRECORDING, VISIONCOMMAND_SKELETONINFO, VISIONCOMMAND_NONE};
enum ENUM_VISIONSTATUS{VISIONSTATUS_RECORDING, VISIONSTATUS_NONE};


#endif /* SKELETONSTREAMING_H_ */
